stages:
  - build
  - release

Build:
  variables:
    VERSION: "0.2.0"
  stage: build
  image: golang:1.21.0
  script:
    - GOOS=linux   GOARCH=amd64 go build -ldflags="-X forklift/Commands.Version=$VERSION" -o bin/forklift-linux-amd64
    - GOOS=darwin  GOARCH=amd64 go build -ldflags="-X forklift/Commands.Version=$VERSION" -o bin/forklift-apple-amd64 -tags no_lzma2
    - GOOS=darwin  GOARCH=arm64 go build -ldflags="-X forklift/Commands.Version=$VERSION" -o bin/forklift-apple-arm64 -tags no_lzma2
    - GOOS=windows GOARCH=amd64 go build -ldflags="-X forklift/Commands.Version=$VERSION" -o bin/forklift-win-amd64   -tags no_lzma2
    - ls -al bin
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/forklift-linux-amd64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/forklift/$VERSION/forklift-linux-amd64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/forklift-apple-amd64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/forklift/$VERSION/forklift-apple-amd64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/forklift-apple-arm64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/forklift/$VERSION/forklift-apple-arm64"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/forklift-win-amd64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/forklift/$VERSION/forklift-win-amd64"'
  tags:
    - kubernetes-parity-build


