[general]
logLevel = "info"
packageSuffix = "some_suffix"
threadscount = 10

[cache]
extraEnv = ["SOME_VAR"]

[cache.extraMetadata]
  github_run_id="$GITHUB_RUN_ID"
  github_job="$GITHUB_JOB"

[compression]
type = "zstd"

[compression.zstd]
compressionLevel = 3


[storage]
type = "fs"

[storage.fs]
directory = "/forklift_fs_storage/cargo"

[storage.s3]
useSsl = true
accessKeyId = "ABCDEF1234567890"
bucketName = "forklift"
endpointUrl = "https://storage.googleapis.com"
secretAccessKey = "very_secret_key"


[metrics]
enabled = false
pushEndpoint = "https://my-prometheus/api/v1/write"

[metrics.extraLabels]
project_name = "cargo"