[general]
loglevel = "info"
packagesuffix = "some_suffix"
threadscount = 10


[compression]
type = "zstd"

[compression.zstd]
compressionLevel = 3


[storage]
type = "fs"

[storage.fs]
directory = "/forklift_fs_storage/cargo"

[storage.s3]
useSsl = true
accessKeyId = "ABCDEF1234567890"
bucketName = "forklift"
endpointUrl = "https://storage.googleapis.com"
secretAccessKey = "very_secret_key"


[metrics]
enabled = false
pushEndpoint = "https://my-prometheus/api/v1/write"

[metrics.extraLabels]
project_name = "cargo"