/// Data generated by build.rs
pub static GENERATED_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/generated_data.bin"));

pub fn get_data() -> &'static [u8] {
    GENERATED_DATA
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_data() {
        assert!(!get_data().is_empty());
    }
}
