name: Build cargo
run-name: Build cargo for `${{ github.ref_name }}`
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  #
  Build-cargo:
    name: Build cargo
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:2024.5.7
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: rootroot
          MINIO_DEFAULT_BUCKETS: forklift:public
        ports:
          - 9000:9000

    steps:
      - id: prepare-composite
        uses: .github/workflows/composite-prepare-cargo.yml
        with:
          path: .

      - run: forklift cargo build --release

      
  Rebuild-cargo:
    needs: Build-cargo
    name: Rebuild cargo
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:2024.5.7
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: rootroot
          MINIO_DEFAULT_BUCKETS: forklift:public
        ports:
          - 9000:9000
    
    strategy:
      matrix:
        path: [cargo1, cargo2]
    steps:
      - id: prepare-composite
        uses: .github/workflows/composite-prepare-cargo.yml
        with:
          path: ./${{ matrix.path }}

      - run: forklift cargo build --release
        working-directory: ./${{ matrix.path }}