name: Build cargo
run-name: Build cargo for `${{ github.ref_name }}`
on:
  push:
    branches:
      - main
      - es/tests
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  #
  Build-cargo:
    name: Build cargo
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:2024.5.7
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: rootroot
          MINIO_DEFAULT_BUCKETS: forklift:public
        ports:
          - 9000:9000

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable          

      - uses: actions/checkout@v4
      - run: |
          go build -o ./bin/forklift
          chmod +x ./bin/forklift
          cp ./bin/forklift /usr/local/bin/
  
      - run: |
          mkdir .forklift
          tee .forklift/config.toml <<< '
          [general]
            logLevel = "trace"
            threadsCount = 3
          [compression]
            type = "none"
          [storage]
            type = "s3"
          [storage.s3]
            endpointUrl = "http://localhost:9000"
            bucketName = "forklift"
            useSSL = false
          '          

      - name: Checkout cargo 1
        uses: actions/checkout@v4
        with:
          repository: rust-lang/cargo
          ref: rust-1.77.0
          path: ./cargo-1
      - run: cp -r .forklift ./cargo-1
      - name: build cargo
        run: forklift cargo build --release
        working-directory: ./cargo-1

      - name: Checkout cargo 2
        uses: actions/checkout@v4
        with:
          repository: rust-lang/cargo
          ref: rust-1.77.0
          path: ./cargo-2
      - run: cp -r .forklift ./cargo-2
      - name: build cargo
        run: forklift cargo build --release
        working-directory: ./cargo-2