name: Check changes files

inputs:
  path:
    type: string
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Checkout cargo
      uses: actions/checkout@v4
      with:
        repository: rust-lang/cargo
        ref: rust-1.77.0
        path: ${{ inputs.path }}

    - name: Checkout forklift
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}/.forklift/repo

    - run: |
        go build -C .forklift/repo/ -o ../bin/forklift
        chmod +x .forklift/bin/forklift
        cp .forklift/bin/forklift /usr/local/bin/
        mkdir -p .forklift/storage
      working-directory: ${{ inputs.path }}

    - run: |
        tee .forklift/config.toml <<< '
        [general]
          logLevel = "warn"
          threadsCount = 3
        [compression]
          type = "none"
        [storage]
          type = "s3"
        [storage.s3]
          endpointUrl = "http://localhost:9000"
          bucketName = "forklift"
          useSSL = false
        '
      working-directory: ${{ inputs.path }}










name: Build cargo
run-name: Build cargo for `${{ github.ref_name }}`
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  #
  Build-cargo:
    name: Build cargo
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:2024.5.7
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: rootroot
          MINIO_DEFAULT_BUCKETS: forklift:public
        ports:
          - 9000:9000

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout cargo
        uses: actions/checkout@v4
        with:
          repository: rust-lang/cargo
          ref: rust-1.77.0
      - name: Checkout forklift
        uses: actions/checkout@v4
        with:
          path: .forklift/repo

      - run: go build -C .forklift/repo/ -o ../bin/forklift
      - run: chmod +x .forklift/bin/forklift
      - run: cp .forklift/bin/forklift /usr/local/bin/
      - run: mkdir -p .forklift/storage
      - run: |
          tee .forklift/config.toml <<< '
          [general]
            logLevel = "warn"
            threadsCount = 3
          [compression]
            type = "none"
          [storage]
            type = "s3"
          [storage.s3]
            endpointUrl = "http://localhost:9000"
            bucketName = "forklift"
            useSSL = false
          '
      - run: forklift cargo build --release
      - run: rm -rf target/
      - run: forklift cargo build --release
  #