name: GitHub Actions Demo
on: push
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: go test ./... -coverprofile=cover.out
      - run: go tool cover -func=cover.out