name: Tests
run-name: Tests for `${{ github.ref_name }}`
on: push
jobs:
  #
  Test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: go test ./... -coverprofile=cover.out
      - run: go tool cover -func=cover.out