name: Tests
on: push
jobs:
  #
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: go test ./... -coverprofile=cover.out
      - run: go tool cover -func=cover.out
  #
  Cargo-test:
    name: build cargo
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: mkdir
        run: |
          mkdir -p ${{ github.workspace }}/.forklift/repo && \
          mkdir -p ${{ github.workspace }}/.forklift/storage && \
          mkdir -p ${{ github.workspace }}/.forklift/bin

      - name: Checkout cargo
        uses: actions/checkout@v4
        with:
          repository: rust-lang/cargo
          ref: rust-1.77.0

      - name: Checkout forklift
        uses: actions/checkout@v4
        with:
          path: .forklift/repo

      - run: go build -C .forklift/repo/ -o ../bin/forklift
      - run: chmod +x .forklift/bin/forklift
      - run: cp .forklift/bin/forklift /usr/local/bin/
      - run: |
          tee .forklift/config.toml <<< '
          [general]
            logLevel = "warn"
            threadsCount = 5
          [compression]
            type = "none"
          [storage]
            type = "fs"
          [storage.fs]
            directory = "${{ github.workspace }}/.forklift/storage"
          '
      - run: forklift cargo build --release
      - run: rm -rf target/
      - run: forklift cargo build --release
  #